# Generated by Django 4.2.6 on 2025-07-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_portfolio_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog Profiles'},
        ),
    ]
